application: yytakehome
version: gigondas
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

# below, sid == (s)hort(id)
handlers:

- url: /schema/update/.+$
  script: service.schema.update.app
  login: required
  secure: always
  auth_fail_action: redirect

- url: /shorturl/.+$
  script: service.app.query

- url: /shorturl
  script: service.app.create_or_update

- url: /.*
  script: service.app.redirect

libraries:
- name: webapp2
  version: latest

env_variables:
  ADMINISTRATORS: 'sc3141@gmail.com'


