application: yytakehome
version: vougeot
runtime: python27
api_version: 1
threadsafe: true

# below, sid == (s)hort(id)
handlers:

- url: /shorturl/.+$
  script: service.app.query

- url: /shorturl
  script: service.app.create_or_update

- url: /.*
  script: service.app.redirect

libraries:
- name: webapp2
  version: latest

