runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: service_main.instance

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

